### ISSUE TITLE
Virtual Devices "Eine Komponente der HomeMatic Zentrale reagiert nicht mehr."

### ISSUE THREAD

**Issue by omo2002** [angelnu/docker-ccu2#19]
Hi,
I think this issues lasts for some versions now, at least in my installation.
I know about the "Hm-IP" problem, which is not supported. But what about the Virtual Devices ?
I found out that /etc/init.d/S62HMServer during startup fails. 
looking into hmserver.log I found issues like:
de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization ERROR [vert.x-eventloop-thread-7] Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/ttyS0' and
Exception while trying to open serial port. Check configured port '/dev/ttyS0'

I started my docker container with 
docker run --name ccu2 -d --restart=always -p 80:80 -p2000:2000 -p 2001:2001 -p 2002:2002 -p 8181:80 -e PERSISTENT_DIR=/mnt -v /dev:/dev_org -v /sys:/sys_org -v ccu2_data:/mnt --device=/dev/ttyAMA0:/dev_org/ttyAMA0:rwm --device=/dev/ttyS0:/dev_org/ttyS0:rwm --hostname ccu2 <my local image>

Any thoughts about this ? Thanks in advance.

**Comment by omo2002** [comment]
HI,

any updates on this ?

Thanks

**Comment by angelnu** [comment]
Hi @omo2002 - are all the devices failing or only virtual devices? The /dev/ttyS0 is the serial interface in the CCU2 which, I think, is used in case of debugging. The antenna is /dev/mmd_bidcos

Btw: I am considering using https://github.com/jens-maus/RaspberryMatic as base for the image instead of the original firmware since Jens added several improvements on top of the original firmware. Now that I have reworked the build to happen within docker then it is easier to add additional tools needed to extract the content of the raspberry image.

**Comment by omo2002** [comment]
Hi

It is only the serial device failing. Everything else, except HM-IP works.

An improvement could be to reduce the timeout during startup from 600 secs to maybe 10 secs to so.

**Comment by angelnu** [comment]
Timeout reduced.

Unfortunately the latest CCU2 firmware only contains the HMIPserver so I cannot start it as alternative when no IP capable HW is present.

**Comment by andreheuer** [comment]
Hi @angelnu, @omo2002,
I am currently trying to migrate from YAHM to docker container(s). However, I am also struggling with the problem described above. I am ex-/importing the settings from my YAHM CCU (using CCU´s backup functionality) to "your" CCU. I´m also using virtual devices for heating groups. And as the virtual devices fail with the error message, I can neither edit, open, or switch virtual devices. The reason seems to be that a "dual stack" for the communication of HM and HMIP was introduced that require additional kernel drivers (keyword: pivccu-driver) and as docker users the hosts kernel (in my case from BerryBoot), these drivers must be installed in the hosts kernel :-(
I don´t know if an "easy" solution is possible...has anyone any thoughts on this? Or has anyone even a solution on this problem?!

BR
André
