### ISSUE TITLE
docker hub

### ISSUE THREAD

**Issue by TommaHawk** [angelnu/docker-ccu2#5]
I think it would be nice and help a lot people if the image would be available in the docker hub https://hub.docker.com/ is it planned to add it here?

**Comment by angelnu** [comment]
I was concerned about the licensing: this is why I only shared the instructions and not the resulting docker image.

I checked the license in the CCU2 firmaware image and I only find references to the included open source, not an specific license. I also did not have to accept any licenses when downloading the firmware image. Therefore I will assume that I can re-distribute the docker image to docker hub.

I will modify the docker image to detect the type of board at runtime instead of buildtime and also include the license. Then I will upload to docker hub.

**Comment by angelnu** [comment]
Uploaded at https://hub.docker.com/r/angelnu/ccu2/
